[2023-04-14T14:30:14.669+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:30:14.675+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:30:14.681+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:14.681+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:30:14.838+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:14.831+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:30:14.842+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:14.841+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:30:14.860+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:30:14.947+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:14.947+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:30:14.994+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:14.993+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T13:30:00+00:00, run_after=2023-04-14T14:30:00+00:00
[2023-04-14T14:30:15.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.355 seconds
[2023-04-14T14:30:45.265+0000] {processor.py:153} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:30:45.268+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:30:45.272+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:45.272+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:30:45.365+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:45.363+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:30:45.366+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:45.366+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:30:45.377+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:30:45.417+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:45.417+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:30:45.467+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:30:45.467+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:30:45.486+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.231 seconds
[2023-04-14T14:31:16.521+0000] {processor.py:153} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:31:16.524+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:31:16.526+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:16.526+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:31:16.675+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:16.673+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:31:16.680+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:16.680+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:31:16.697+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:31:16.736+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:16.736+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:31:16.773+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:16.773+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:31:16.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.299 seconds
[2023-04-14T14:31:47.719+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:31:47.721+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:31:47.723+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:47.723+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:31:47.771+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:47.769+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:31:47.772+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:47.772+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:31:47.778+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:31:47.801+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:47.801+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:31:47.827+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:31:47.827+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:31:47.839+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.128 seconds
[2023-04-14T14:32:18.685+0000] {processor.py:153} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:32:18.687+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:32:18.690+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:32:18.689+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:32:18.736+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:32:18.734+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:32:18.737+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:32:18.737+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:32:18.742+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:32:18.785+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:32:18.785+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:32:18.817+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:32:18.817+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:32:18.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.151 seconds
[2023-04-14T14:33:37.697+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:33:37.703+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:33:37.705+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:33:37.704+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:33:38.558+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:33:38.543+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:33:38.573+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:33:38.569+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:33:38.736+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:33:39.112+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:33:39.111+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:33:39.180+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:33:39.177+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:33:39.254+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 1.566 seconds
[2023-04-14T14:34:09.952+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:34:09.969+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:34:09.971+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:09.970+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:34:10.326+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:10.278+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:34:10.354+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:10.345+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:34:10.491+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:34:10.662+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:10.662+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:34:10.811+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:10.811+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:34:10.871+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.931 seconds
[2023-04-14T14:34:41.200+0000] {processor.py:153} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:34:41.204+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:34:41.207+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:41.207+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:34:41.396+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:41.394+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:34:41.398+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:41.398+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:34:41.414+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:34:41.491+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:41.488+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:34:41.639+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:41.639+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:34:41.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.499 seconds
[2023-04-14T14:35:12.725+0000] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:35:12.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:35:12.732+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:12.732+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:35:12.893+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:12.890+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:35:12.895+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:12.895+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:35:12.902+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:35:12.938+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:12.938+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:35:12.983+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:12.983+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:35:13.074+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.357 seconds
[2023-04-14T14:35:43.398+0000] {processor.py:153} INFO - Started process (PID=246) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:35:43.412+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:35:43.420+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:43.419+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:35:43.499+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:43.496+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:35:43.502+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:43.501+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:35:43.509+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:35:43.550+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:43.549+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:35:43.604+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:43.604+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:35:43.633+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.252 seconds
[2023-04-14T14:36:14.335+0000] {processor.py:153} INFO - Started process (PID=299) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:36:14.338+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:36:14.340+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:14.340+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:36:14.460+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:14.454+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:36:14.463+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:14.463+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:36:14.474+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:36:14.519+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:14.519+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:36:14.551+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:14.551+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:36:14.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.245 seconds
[2023-04-14T14:36:44.656+0000] {processor.py:153} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:36:44.661+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:36:44.662+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:44.662+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:36:44.771+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:44.766+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:36:44.772+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:44.772+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:36:44.778+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:36:44.803+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:44.803+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:36:44.834+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:44.834+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:36:44.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.198 seconds
[2023-04-14T14:37:15.871+0000] {processor.py:153} INFO - Started process (PID=405) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:37:15.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:37:15.874+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:15.874+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:37:15.943+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:15.940+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:37:15.945+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:15.945+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:37:15.952+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:37:15.981+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:15.981+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:37:16.016+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:16.016+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:37:16.029+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.167 seconds
[2023-04-14T14:37:46.334+0000] {processor.py:153} INFO - Started process (PID=458) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:37:46.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:37:46.338+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:46.338+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:37:46.387+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:46.386+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:37:46.389+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:46.389+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:37:46.395+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:37:46.430+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:46.430+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:37:46.456+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:46.456+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:37:46.469+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.141 seconds
[2023-04-14T14:38:16.740+0000] {processor.py:153} INFO - Started process (PID=510) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:38:16.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:38:16.745+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:16.745+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:38:16.801+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:16.800+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:38:16.803+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:16.803+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:38:16.811+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:38:16.846+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:16.846+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:38:16.892+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:16.892+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:38:16.918+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.206 seconds
[2023-04-14T14:38:47.119+0000] {processor.py:153} INFO - Started process (PID=567) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:38:47.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:38:47.124+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:47.124+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:38:47.186+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:47.184+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:38:47.188+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:47.187+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:38:47.195+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:38:47.221+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:47.221+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:38:47.245+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:47.245+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:38:47.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.153 seconds
[2023-04-14T14:39:18.178+0000] {processor.py:153} INFO - Started process (PID=620) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:39:18.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:39:18.188+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:18.188+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:39:18.258+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:18.257+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:39:18.260+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:18.260+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:39:18.267+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:39:18.291+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:18.291+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:39:18.313+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:18.313+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:39:18.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.154 seconds
[2023-04-14T14:39:49.004+0000] {processor.py:153} INFO - Started process (PID=673) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:39:49.006+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:39:49.008+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:49.008+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:39:49.053+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:49.052+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:39:49.055+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:49.055+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:39:49.060+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:39:49.087+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:49.087+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:39:49.108+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:49.108+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:39:49.121+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.124 seconds
[2023-04-14T14:40:19.840+0000] {processor.py:153} INFO - Started process (PID=726) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:40:19.843+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:40:19.845+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:19.845+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:40:19.899+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:19.897+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:40:19.900+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:19.900+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:40:19.906+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:40:19.938+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:19.938+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:40:19.963+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:19.963+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:40:19.977+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.146 seconds
[2023-04-14T14:40:50.245+0000] {processor.py:153} INFO - Started process (PID=779) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:40:50.249+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:40:50.251+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:50.251+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:40:50.298+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:50.296+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:40:50.299+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:50.299+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:40:50.305+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:40:50.338+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:50.338+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:40:50.364+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:50.364+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:40:50.379+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.147 seconds
[2023-04-14T14:41:20.547+0000] {processor.py:153} INFO - Started process (PID=832) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:41:20.551+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:41:20.553+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:41:20.552+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:41:20.609+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:41:20.608+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:41:20.610+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:41:20.610+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:41:20.616+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:41:20.640+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:41:20.640+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:41:20.679+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:41:20.679+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:41:20.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.154 seconds
[2023-04-14T14:42:11.123+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:42:11.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:42:11.137+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:11.136+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:42:11.293+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:11.291+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:42:11.298+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:11.297+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:42:11.312+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:42:11.499+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:11.498+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:42:11.618+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:11.618+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:42:11.679+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.564 seconds
[2023-04-14T14:42:41.815+0000] {processor.py:153} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:42:41.818+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:42:41.821+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:41.821+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:42:41.978+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:41.976+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:42:41.985+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:41.984+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:42:42.009+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:42:42.044+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:42.044+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:42:42.079+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:42.078+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:42:42.093+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.288 seconds
[2023-04-14T14:43:12.335+0000] {processor.py:153} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:43:12.338+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:43:12.344+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:12.341+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:43:12.479+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:12.476+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:43:12.483+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:12.483+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:43:12.508+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:43:12.555+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:12.555+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:43:12.580+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:12.580+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:43:12.595+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.271 seconds
[2023-04-14T14:43:42.642+0000] {processor.py:153} INFO - Started process (PID=194) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:43:42.643+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:43:42.644+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:42.644+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:43:42.688+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:42.687+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:43:42.690+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:42.689+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:43:42.697+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:43:42.720+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:42.720+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:43:42.740+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:42.740+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:43:42.751+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.113 seconds
[2023-04-14T14:44:12.812+0000] {processor.py:153} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:44:12.814+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:44:12.815+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:12.815+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:44:12.845+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:12.845+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:44:12.847+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:12.847+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:44:12.853+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:44:12.876+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:12.876+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:44:12.899+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:12.899+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:44:12.914+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.105 seconds
[2023-04-14T14:44:42.968+0000] {processor.py:153} INFO - Started process (PID=300) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:44:42.970+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:44:42.972+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:42.972+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:44:43.003+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:43.002+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:44:43.004+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:43.004+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:44:43.011+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:44:43.037+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:43.037+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:44:43.071+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:43.071+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:44:43.085+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.123 seconds
[2023-04-14T14:45:13.334+0000] {processor.py:153} INFO - Started process (PID=353) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:45:13.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:45:13.338+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:13.338+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:45:13.422+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:13.418+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:45:13.425+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:13.425+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:45:13.440+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:45:13.463+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:13.463+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:45:13.485+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:13.485+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:45:13.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.175 seconds
[2023-04-14T14:45:43.715+0000] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:45:43.717+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:45:43.718+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:43.718+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:45:43.774+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:43.773+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:45:43.775+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:43.774+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:45:43.783+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:45:43.803+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:43.803+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:45:43.822+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:43.822+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:45:43.833+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.126 seconds
[2023-04-14T14:46:14.233+0000] {processor.py:153} INFO - Started process (PID=459) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:46:14.235+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:46:14.236+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:14.236+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:46:14.291+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:14.289+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:46:14.292+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:14.292+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:46:14.300+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:46:14.322+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:14.322+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:46:14.347+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:14.347+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:46:14.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.132 seconds
[2023-04-14T14:46:44.502+0000] {processor.py:153} INFO - Started process (PID=512) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:46:44.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:46:44.505+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:44.505+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:46:44.559+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:44.558+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:46:44.561+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:44.560+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:46:44.570+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:46:44.590+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:44.589+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:46:44.608+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:44.608+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:46:44.619+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.123 seconds
[2023-04-14T14:47:14.735+0000] {processor.py:153} INFO - Started process (PID=566) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:47:14.738+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:47:14.739+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:14.739+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:47:14.804+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:14.798+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:47:14.809+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:14.809+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:47:14.821+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:47:14.858+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:14.858+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:47:14.881+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:14.881+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:47:14.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.170 seconds
[2023-04-14T14:47:45.452+0000] {processor.py:153} INFO - Started process (PID=620) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:47:45.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:47:45.455+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:45.455+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:47:45.502+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:45.500+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:47:45.503+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:45.503+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:47:45.512+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:47:45.538+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:45.538+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:47:45.559+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:45.559+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:47:45.571+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.127 seconds
[2023-04-14T14:48:16.109+0000] {processor.py:153} INFO - Started process (PID=672) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:48:16.111+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:48:16.112+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:16.112+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:48:16.150+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:16.149+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:48:16.151+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:16.151+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:48:16.159+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:48:16.185+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:16.185+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:48:16.221+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:16.221+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:48:16.235+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.131 seconds
[2023-04-14T14:48:46.339+0000] {processor.py:153} INFO - Started process (PID=725) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:48:46.341+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:48:46.342+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:46.342+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:48:46.391+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:46.390+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:48:46.393+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:46.393+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:48:46.400+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:48:46.423+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:46.423+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:48:46.445+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:46.445+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:48:46.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.128 seconds
[2023-04-14T14:49:16.821+0000] {processor.py:153} INFO - Started process (PID=778) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:49:16.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:49:16.825+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:16.825+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:49:16.885+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:16.884+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:49:16.887+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:16.887+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:49:16.896+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:49:16.931+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:16.931+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:49:16.958+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:16.957+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:49:16.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.168 seconds
[2023-04-14T14:49:47.145+0000] {processor.py:153} INFO - Started process (PID=831) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:49:47.147+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:49:47.148+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:47.148+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:49:47.188+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:47.187+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:49:47.189+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:47.189+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:49:47.201+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:49:47.234+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:47.234+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:49:47.255+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:47.255+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:49:47.267+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.130 seconds
[2023-04-14T14:50:17.945+0000] {processor.py:153} INFO - Started process (PID=884) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:50:17.947+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:50:17.949+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:17.949+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:50:18.010+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:18.009+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:50:18.011+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:18.011+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:50:18.020+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:50:18.045+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:18.045+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:50:18.065+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:18.065+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:50:18.077+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.140 seconds
[2023-04-14T14:50:48.385+0000] {processor.py:153} INFO - Started process (PID=938) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:50:48.387+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:50:48.389+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:48.388+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:50:48.476+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:48.475+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:50:48.478+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:48.478+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:50:48.486+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:50:48.530+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:48.530+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:50:48.555+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:48.555+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:50:48.568+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.189 seconds
[2023-04-14T14:51:19.398+0000] {processor.py:153} INFO - Started process (PID=990) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:51:19.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:51:19.401+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:19.401+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:51:19.447+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:19.446+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:51:19.448+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:19.448+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:51:19.456+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:51:19.497+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:19.497+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:51:19.520+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:19.520+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:51:19.533+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.142 seconds
[2023-04-14T14:51:49.765+0000] {processor.py:153} INFO - Started process (PID=1044) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:51:49.766+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:51:49.768+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:49.768+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:51:49.811+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:49.810+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:51:49.812+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:49.812+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:51:49.819+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:51:49.842+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:49.842+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:51:49.861+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:49.861+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:51:49.879+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.121 seconds
[2023-04-14T14:52:20.126+0000] {processor.py:153} INFO - Started process (PID=1096) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:52:20.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:52:20.129+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:20.129+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:52:20.179+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:20.176+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:52:20.181+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:20.181+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:52:20.189+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:52:20.216+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:20.215+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:52:20.235+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:20.235+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:52:20.248+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.129 seconds
[2023-04-14T14:52:50.620+0000] {processor.py:153} INFO - Started process (PID=1149) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:52:50.623+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:52:50.625+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:50.625+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:52:50.666+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:50.665+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:52:50.667+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:50.667+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:52:50.674+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:52:50.701+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:50.701+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:52:50.734+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:50.733+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:52:50.747+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.146 seconds
[2023-04-14T14:53:21.037+0000] {processor.py:153} INFO - Started process (PID=1201) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:53:21.040+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:53:21.042+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:21.042+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:53:21.084+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:21.083+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:53:21.085+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:21.085+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:53:21.093+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:53:21.131+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:21.131+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:53:21.153+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:21.153+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:53:21.166+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.146 seconds
[2023-04-14T14:53:51.294+0000] {processor.py:153} INFO - Started process (PID=1253) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:53:51.296+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:53:51.298+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:51.297+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:53:51.351+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:51.350+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:53:51.352+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:51.352+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:53:51.360+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:53:51.387+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:51.387+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:53:51.408+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:51.408+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:53:51.421+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.137 seconds
[2023-04-14T14:54:21.610+0000] {processor.py:153} INFO - Started process (PID=1306) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:54:21.612+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:54:21.614+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:21.613+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:54:21.674+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:21.673+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:54:21.676+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:21.675+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:54:21.684+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:54:21.719+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:21.719+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:54:21.747+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:21.747+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:54:21.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.158 seconds
[2023-04-14T14:54:52.022+0000] {processor.py:153} INFO - Started process (PID=1359) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:54:52.025+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:54:52.027+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:52.027+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:54:52.066+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:52.065+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:54:52.067+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:52.067+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:54:52.073+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:54:52.097+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:52.097+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:54:52.128+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:52.128+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:54:52.140+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.126 seconds
[2023-04-14T14:55:22.535+0000] {processor.py:153} INFO - Started process (PID=1411) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:55:22.537+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:55:22.538+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:22.538+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:55:22.575+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:22.574+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:55:22.578+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:22.578+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:55:22.585+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:55:22.623+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:22.623+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:55:22.647+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:22.646+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:55:22.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.128 seconds
[2023-04-14T14:55:52.781+0000] {processor.py:153} INFO - Started process (PID=1463) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:55:52.784+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:55:52.785+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:52.785+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:55:52.846+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:52.845+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:55:52.848+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:52.848+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:55:52.856+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:55:52.901+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:52.901+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:55:52.937+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:52.937+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:55:52.953+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.177 seconds
[2023-04-14T14:56:23.168+0000] {processor.py:153} INFO - Started process (PID=1516) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:56:23.171+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:56:23.172+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:23.172+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:56:23.214+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:23.213+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:56:23.215+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:23.215+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:56:23.221+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:56:23.248+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:23.248+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:56:23.279+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:23.279+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:56:23.292+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.139 seconds
[2023-04-14T14:56:53.788+0000] {processor.py:153} INFO - Started process (PID=1569) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:56:53.790+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:56:53.791+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:53.791+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:56:53.826+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:53.824+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:56:53.827+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:53.827+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:56:53.844+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:56:53.873+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:53.872+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:56:53.893+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:53.893+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:56:53.905+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.121 seconds
[2023-04-14T14:57:24.026+0000] {processor.py:153} INFO - Started process (PID=1622) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:57:24.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T14:57:24.031+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:57:24.030+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:57:24.123+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:57:24.122+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T14:57:24.125+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:57:24.125+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T14:57:24.137+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T14:57:24.243+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:57:24.243+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T14:57:24.300+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:57:24.300+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T14:57:24.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 0.322 seconds
[2023-04-14T15:05:37.026+0000] {processor.py:153} INFO - Started process (PID=1631) to work on /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T15:05:37.072+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_executa_sql.py for tasks to queue
[2023-04-14T15:05:37.091+0000] {logging_mixin.py:137} INFO - [2023-04-14T15:05:37.090+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T15:05:38.088+0000] {logging_mixin.py:137} INFO - [2023-04-14T15:05:38.064+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-14T15:05:38.591+0000] {logging_mixin.py:137} INFO - [2023-04-14T15:05:38.516+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insere_dados_tabela_db.sql
[2023-04-14T15:05:39.377+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag_executa_sql']) retrieved from /opt/airflow/dags/dag_executa_sql.py
[2023-04-14T15:05:41.981+0000] {logging_mixin.py:137} INFO - [2023-04-14T15:05:41.975+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-04-14T15:05:42.783+0000] {logging_mixin.py:137} INFO - [2023-04-14T15:05:42.762+0000] {dag.py:3444} INFO - Setting next_dagrun for dag_executa_sql to 2023-04-14T14:30:00+00:00, run_after=2023-04-14T15:30:00+00:00
[2023-04-14T15:05:43.117+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_executa_sql.py took 6.165 seconds
