[2023-04-14T14:33:36.943+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:33:36.985+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:33:37.011+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:33:37.010+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:33:37.203+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:33:37.165+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:33:37.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:33:37.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.673 seconds
[2023-04-14T14:34:07.882+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:34:07.887+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:34:07.892+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:07.892+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:34:07.996+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:07.961+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:34:08.000+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:34:08.169+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.332 seconds
[2023-04-14T14:34:39.107+0000] {processor.py:153} INFO - Started process (PID=139) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:34:39.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:34:39.124+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:39.123+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:34:39.197+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:34:39.189+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:34:39.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:34:39.321+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.229 seconds
[2023-04-14T14:35:09.585+0000] {processor.py:153} INFO - Started process (PID=192) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:35:09.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:35:09.588+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:09.588+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:35:09.606+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:09.603+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:35:09.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:35:09.650+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.071 seconds
[2023-04-14T14:35:40.151+0000] {processor.py:153} INFO - Started process (PID=245) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:35:40.153+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:35:40.154+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:40.154+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:35:40.171+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:35:40.169+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:35:40.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:35:40.220+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.088 seconds
[2023-04-14T14:36:11.237+0000] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:36:11.240+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:36:11.242+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:11.242+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:36:11.257+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:11.255+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:36:11.258+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:36:11.300+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.069 seconds
[2023-04-14T14:36:41.442+0000] {processor.py:153} INFO - Started process (PID=351) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:36:41.444+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:36:41.447+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:41.447+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:36:41.478+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:36:41.471+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:36:41.483+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:36:41.540+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.104 seconds
[2023-04-14T14:37:11.709+0000] {processor.py:153} INFO - Started process (PID=404) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:37:11.712+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:37:11.713+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:11.713+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:37:11.731+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:11.728+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:37:11.731+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:37:11.751+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.049 seconds
[2023-04-14T14:37:42.235+0000] {processor.py:153} INFO - Started process (PID=457) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:37:42.237+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:37:42.238+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:42.238+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:37:42.255+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:37:42.253+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:37:42.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:37:42.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.074 seconds
[2023-04-14T14:38:12.577+0000] {processor.py:153} INFO - Started process (PID=509) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:12.580+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:38:12.581+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:12.581+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:12.599+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:12.597+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from src.tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'src'
[2023-04-14T14:38:12.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:12.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.095 seconds
[2023-04-14T14:38:18.290+0000] {processor.py:153} INFO - Started process (PID=515) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:18.292+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:38:18.293+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:18.293+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:18.309+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:18.308+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:38:18.310+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:18.337+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.051 seconds
[2023-04-14T14:38:20.620+0000] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:20.622+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:38:20.624+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:20.624+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:20.645+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:20.643+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:38:20.646+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:20.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.059 seconds
[2023-04-14T14:38:28.514+0000] {processor.py:153} INFO - Started process (PID=531) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:28.515+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:38:28.516+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:28.516+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:28.529+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:28.528+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:38:28.530+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:28.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.036 seconds
[2023-04-14T14:38:32.247+0000] {processor.py:153} INFO - Started process (PID=549) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:32.250+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:38:32.252+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:32.252+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:32.313+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:32.304+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:38:32.316+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:32.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.130 seconds
[2023-04-14T14:38:35.144+0000] {processor.py:153} INFO - Started process (PID=555) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:35.147+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:38:35.149+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:35.149+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:35.182+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:38:35.180+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:38:35.183+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:38:35.220+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.087 seconds
[2023-04-14T14:39:06.065+0000] {processor.py:153} INFO - Started process (PID=608) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:39:06.068+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:39:06.069+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:06.069+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:39:06.084+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:06.080+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:39:06.087+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:39:06.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.089 seconds
[2023-04-14T14:39:36.935+0000] {processor.py:153} INFO - Started process (PID=661) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:39:36.937+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:39:36.938+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:36.938+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:39:36.949+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:39:36.947+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:39:36.950+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:39:36.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.058 seconds
[2023-04-14T14:40:07.767+0000] {processor.py:153} INFO - Started process (PID=714) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:40:07.771+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:40:07.773+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:07.772+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:40:07.807+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:07.805+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:40:07.808+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:40:07.841+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.087 seconds
[2023-04-14T14:40:38.455+0000] {processor.py:153} INFO - Started process (PID=767) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:40:38.458+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:40:38.459+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:38.459+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:40:38.472+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:40:38.470+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:40:38.473+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:40:38.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.052 seconds
[2023-04-14T14:41:08.714+0000] {processor.py:153} INFO - Started process (PID=820) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:41:08.724+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:41:08.728+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:41:08.727+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:41:08.758+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:41:08.755+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:41:08.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:41:08.790+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.084 seconds
[2023-04-14T14:42:10.868+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:42:10.871+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:42:10.874+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:10.874+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:42:10.924+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:10.919+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:42:10.935+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:42:11.047+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.189 seconds
[2023-04-14T14:42:41.772+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:42:41.777+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:42:41.781+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:41.781+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:42:41.832+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:42:41.821+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:42:41.845+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:42:41.930+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.171 seconds
[2023-04-14T14:43:12.330+0000] {processor.py:153} INFO - Started process (PID=140) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:43:12.337+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:43:12.343+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:12.343+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:43:12.423+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:12.419+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:43:12.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:43:12.492+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.169 seconds
[2023-04-14T14:43:42.623+0000] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:43:42.625+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:43:42.627+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:42.626+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:43:42.643+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:43:42.642+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:43:42.644+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:43:42.664+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.048 seconds
[2023-04-14T14:44:12.745+0000] {processor.py:153} INFO - Started process (PID=246) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:44:12.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:44:12.749+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:12.748+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:44:12.764+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:12.762+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:44:12.765+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:44:12.790+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.053 seconds
[2023-04-14T14:44:42.891+0000] {processor.py:153} INFO - Started process (PID=299) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:44:42.893+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:44:42.896+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:42.896+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:44:42.916+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:44:42.914+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:44:42.916+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:44:42.939+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.054 seconds
[2023-04-14T14:45:13.329+0000] {processor.py:153} INFO - Started process (PID=352) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:45:13.333+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:45:13.336+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:13.336+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:45:13.369+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:13.358+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:45:13.372+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:45:13.431+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.108 seconds
[2023-04-14T14:45:43.712+0000] {processor.py:153} INFO - Started process (PID=405) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:45:43.715+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:45:43.716+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:43.716+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:45:43.734+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:45:43.732+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:45:43.735+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:45:43.766+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.062 seconds
[2023-04-14T14:46:14.227+0000] {processor.py:153} INFO - Started process (PID=458) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:46:14.229+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:46:14.231+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:14.231+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:46:14.249+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:14.247+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:46:14.250+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:46:14.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.064 seconds
[2023-04-14T14:46:44.501+0000] {processor.py:153} INFO - Started process (PID=511) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:46:44.503+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:46:44.505+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:44.505+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:46:44.528+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:46:44.524+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:46:44.529+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:46:44.558+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.066 seconds
[2023-04-14T14:47:14.736+0000] {processor.py:153} INFO - Started process (PID=565) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:14.738+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:47:14.739+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:14.739+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:14.756+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:14.754+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:47:14.757+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:14.795+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.075 seconds
[2023-04-14T14:47:45.452+0000] {processor.py:153} INFO - Started process (PID=619) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:45.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:47:45.455+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:45.455+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:45.473+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:45.471+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:47:45.474+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:45.502+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.058 seconds
[2023-04-14T14:47:47.636+0000] {processor.py:153} INFO - Started process (PID=621) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:47.639+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:47:47.640+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:47.640+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:47.665+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:47:47.663+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:47:47.665+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:47:47.707+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.081 seconds
[2023-04-14T14:48:18.218+0000] {processor.py:153} INFO - Started process (PID=673) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:48:18.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:48:18.224+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:18.224+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:48:18.238+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:18.236+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:48:18.239+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:48:18.280+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.074 seconds
[2023-04-14T14:48:48.407+0000] {processor.py:153} INFO - Started process (PID=726) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:48:48.409+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:48:48.411+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:48.411+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:48:48.424+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:48:48.422+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:48:48.425+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:48:48.445+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.044 seconds
[2023-04-14T14:49:18.883+0000] {processor.py:153} INFO - Started process (PID=779) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:49:18.890+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:49:18.892+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:18.892+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:49:18.923+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:18.919+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:49:18.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:49:18.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.085 seconds
[2023-04-14T14:49:49.213+0000] {processor.py:153} INFO - Started process (PID=832) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:49:49.215+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:49:49.217+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:49.217+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:49:49.229+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:49:49.227+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:49:49.230+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:49:49.252+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.047 seconds
[2023-04-14T14:50:20.011+0000] {processor.py:153} INFO - Started process (PID=885) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:50:20.013+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:50:20.014+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:20.014+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:50:20.026+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:20.024+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:50:20.027+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:50:20.047+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.043 seconds
[2023-04-14T14:50:50.456+0000] {processor.py:153} INFO - Started process (PID=939) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:50:50.458+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:50:50.459+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:50.459+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:50:50.471+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:50:50.469+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:50:50.471+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:50:50.493+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.045 seconds
[2023-04-14T14:51:20.582+0000] {processor.py:153} INFO - Started process (PID=991) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:51:20.584+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:51:20.586+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:20.586+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:51:20.603+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:20.601+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:51:20.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:51:20.624+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.048 seconds
[2023-04-14T14:51:50.804+0000] {processor.py:153} INFO - Started process (PID=1045) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:51:50.808+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:51:50.810+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:50.810+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:51:50.824+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:51:50.822+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:51:50.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:51:50.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.050 seconds
[2023-04-14T14:52:21.177+0000] {processor.py:153} INFO - Started process (PID=1097) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:52:21.179+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:52:21.181+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:21.180+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:52:21.194+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:21.192+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:52:21.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:52:21.215+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.043 seconds
[2023-04-14T14:52:51.634+0000] {processor.py:153} INFO - Started process (PID=1150) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:52:51.637+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:52:51.638+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:51.638+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:52:51.650+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:52:51.649+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:52:51.651+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:52:51.672+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.046 seconds
[2023-04-14T14:53:22.045+0000] {processor.py:153} INFO - Started process (PID=1202) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:53:22.047+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:53:22.049+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:22.049+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:53:22.058+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:22.057+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:53:22.060+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:53:22.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.039 seconds
[2023-04-14T14:53:52.311+0000] {processor.py:153} INFO - Started process (PID=1254) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:53:52.313+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:53:52.315+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:52.315+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:53:52.326+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:53:52.324+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:53:52.326+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:53:52.345+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.040 seconds
[2023-04-14T14:54:22.639+0000] {processor.py:153} INFO - Started process (PID=1307) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:54:22.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:54:22.643+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:22.643+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:54:22.656+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:22.654+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:54:22.656+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:54:22.678+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.045 seconds
[2023-04-14T14:54:53.060+0000] {processor.py:153} INFO - Started process (PID=1360) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:54:53.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:54:53.064+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:53.063+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:54:53.076+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:54:53.074+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:54:53.077+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:54:53.097+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.044 seconds
[2023-04-14T14:55:23.581+0000] {processor.py:153} INFO - Started process (PID=1412) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:55:23.585+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:55:23.587+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:23.587+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:55:23.603+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:23.601+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:55:23.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:55:23.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.053 seconds
[2023-04-14T14:55:53.823+0000] {processor.py:153} INFO - Started process (PID=1464) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:55:53.829+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:55:53.831+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:53.831+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:55:53.848+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:55:53.846+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:55:53.849+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:55:53.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.056 seconds
[2023-04-14T14:56:24.160+0000] {processor.py:153} INFO - Started process (PID=1517) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:56:24.162+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:56:24.163+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:24.163+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:56:24.172+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:24.170+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:56:24.173+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:56:24.191+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.035 seconds
[2023-04-14T14:56:54.835+0000] {processor.py:153} INFO - Started process (PID=1570) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:56:54.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:56:54.839+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:54.839+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:56:54.852+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:56:54.850+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:56:54.853+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:56:54.873+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.044 seconds
[2023-04-14T14:57:25.054+0000] {processor.py:153} INFO - Started process (PID=1623) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:57:25.058+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T14:57:25.063+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:57:25.063+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:57:25.084+0000] {logging_mixin.py:137} INFO - [2023-04-14T14:57:25.082+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T14:57:25.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T14:57:25.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 0.098 seconds
[2023-04-14T15:05:33.142+0000] {processor.py:153} INFO - Started process (PID=1629) to work on /opt/airflow/dags/pipeline_dag.py
[2023-04-14T15:05:33.170+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/pipeline_dag.py for tasks to queue
[2023-04-14T15:05:33.182+0000] {logging_mixin.py:137} INFO - [2023-04-14T15:05:33.182+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T15:05:33.490+0000] {logging_mixin.py:137} INFO - [2023-04-14T15:05:33.460+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline_dag.py", line 3, in <module>
    from tasks.compare_model import compare_model
ModuleNotFoundError: No module named 'tasks'
[2023-04-14T15:05:33.515+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline_dag.py
[2023-04-14T15:05:35.407+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/pipeline_dag.py took 2.333 seconds
